source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

pod 'GoogleMaps'
pod 'GoogleAnalytics', '~>3.12.0'
pod 'GoogleSignIn', '~> 2.1'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '>= 2.2'