# Uncomment this line to define a global platform for your project
platform :ios, '8.4'
use_frameworks!

def all_pods
    pod 'GoogleMaps',       '>= 1.10.3'
    pod 'Google/Analytics', '>= 1.1.0'
    pod 'GoogleSignIn',     '>= 2.2.0'
    
    pod 'FBSDKCoreKit',     '>= 4.8.0'
    pod 'FBSDKLoginKit',    '>= 4.8.0'
    
    pod 'Firebase',         '>= 2.4.3'
    pod 'GeoFire',          '>= 1.1.2'
    
    pod 'DZNEmptyDataSet',  '>= 1.7.2'
    
    pod 'Alamofire',        '>= 3.1.3'
    pod 'SwiftyJSON',       '>= 2.3.0'
    
end

target 'Hunger Free City' do
    all_pods
end

target 'Hunger Free CityTests' do
    all_pods
end
