# Uncomment this line to define a global platform for your project
platform :ios, '8.4'
use_frameworks!

def all_pods
    pod 'GoogleMaps'
    pod 'Google/Analytics', '~>1.0.0'
    pod 'GoogleSignIn', '~> 2.1'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    
    pod 'DZNEmptyDataSet'
    
    pod 'Alamofire', '~> 1.3'
    pod 'SwiftyJSON', '~> 2.2'
end

target 'Hunger Free City' do
    all_pods
end

target 'Hunger Free CityTests' do
    all_pods
end
